# Generated by Django 3.2.9 on 2022-08-04 19:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problematica', models.TextField(default='Sin asignar', max_length=25)),
                ('desc', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=-1)),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='media/mushroom.png', null=True, upload_to='media/')),
                ('bio', models.TextField(default='Usuario misterioso...')),
                ('birthday', models.DateField(default=datetime.datetime.today)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileScoreLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
                ('scoreDate', models.DateTimeField(default=datetime.datetime(2022, 8, 4, 19, 44, 30, 541627, tzinfo=utc))),
                ('avgScoreTime', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('avgMomevemts', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('levelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
                ('scoreDate', models.DateTimeField(default=datetime.datetime(2022, 8, 4, 19, 44, 30, 541627, tzinfo=utc))),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('levelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
                ('profileID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
