# Generated by Django 3.2.9 on 2022-08-04 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilescore',
            name='scoreDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 19, 49, 12, 348383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profilescorelogic',
            name='avgMomevemts',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profilescorelogic',
            name='scoreDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 19, 49, 12, 348383, tzinfo=utc)),
        ),
    ]
